####### BOOTSTRAP ########
ansible_user: dataops
initial_user: root
bootstrap_user: dataops
backup_user: dataops_backup
github_pubkeys:
  - Bee0933

upgrade_all_packages: false
docker_users: "{{bootstrap_user}}"
docker_daily_prune: true

####### src-server ########
sftp_user: dataops
sftp_password: dataops
sftp_dir: /home/{{ ansible_user }}/sftp_data
sftp_remote_dir: /home/sftp
sftp_template_data: "{{ sftp_dir }}/template"
sftp_docker_image: emberstack/sftp
sftp_port: 2222
files_to_upload:                       # List of files to upload
  - "for-hire.csv"
  - "green-taxi.csv"
  - "yellow-taxi.csv"

# postgres DWH
postgres_docker_image: postgres
postgres_docker_image_tag: 13
postgres_container_name: postgres_dwh
postgres_database: postgres
postgres_password: root
postgres_user: root
postgres_port: 5432
postgres_dwh_user: dataops
postgres_dwh_user_password: dataops
postgres_dwh_database: dataops_db
postgres_data_dir: /opt/postgres/data
postgres_config_dir: /opt/postgres/config
postgres_log_dir: /var/log/postgresql
# pg configs
pg_addr: 0.0.0.0/0
pg_shared_buffers: 1GB
pg_work_mem: 16MB
pg_maintenance_work_mem: 512MB
pg_max_connections: 100


###### Airbtye-server ######
airbyte_email: user@dataops.com
airtbyte_pasword: dataops
airbyte_iac_path: /templates/
airbyte_sftp_src_dir: /sftp
airbyte_port: 8000
airbyte_sftp_filetype: csv
airbyte_sftp_file_pattern: ".*\\.csv"
airbyte_sync_mode: full_refresh_append
airbyte_src_stream_name_1: yellow-taxi.csv
airbyte_src_stream_name_2: green-taxi.csv
airbyte_src_stream_name_3: for-hire.csv
airbyte_sync_cron: 0 0 * * * ?


###### Storage Server #######
minio_docker_image: quay.io/minio/minio
minio_docker_image_tag: latest
minio_container_name: minio
minio_base_dir: ./minio
minio_data_dir: minio/data
minio_console_port: 9001
minio_api_port: 9000
minio_root_usr: dataops
minio_root_password: dataops123
minio_mc_docker_image: minio/mc
minio_mc_docker_image_tag: latest
minio_mc_client: dmlminio
minio_bucket_name: rawdata
minio_bucket_path: /
minio_bucket_region: us-east-1


######## Query Layer #########
duckdb_svc_container_name: duckdb-query-service
duckdb_svc_image: bestnyah/duckdb-query-service
duckdb_svc_image_tag: latest
duckdb_svc_container_port: "8007"


####### Monitor ########
node_exporter_container_name: node_exporter
node_exporter_container_image: prom/node-exporter:v1.5.0 #TODO update to v1.7.0
node_exporter_container_env: {}
node_exporter_container_ports:
  - 9100:9100
node_exporter_container_volumes:
  - /proc:/host/proc:ro
  - /sys:/host/sys:ro
  - /:/rootfs:ro
node_exporter_container_stop_timeout: "30"
node_exporter_container_networks:
  - name: host
node_exporter_container_command:
  - --path.procfs=/host/proc
  - --path.rootfs=/rootfs
  - --path.sysfs=/host/sys
  - --collector.filesystem.ignored-mount-points
  - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/doc

# promtail
promtail_dir: "/etc/promtail"
promtail_config_file_path: "{{promtail_dir}}/promtail.yml"
promtail_docker_version: 2.8.8
promrtail_http_listen_port: 9080
loki_push_url: ""
loki_basic_auth_user: ""
loki_basic_auth_password: ""


###### Nginx ##########
nginx_container_name: nginx
home_dir: /home/{{ bootstrap_user }}
nginx_dir: "{{ home_dir }}/nginx"
nginx_conf_file: nginx.conf.j2
nginx_auth_user: dataops
nginx_auth_password: "IdP5uAZywN"
nginx_node_exporter_local_port: 9100
nginx_node_exporter_public_port: 39100
nginx_promtail_local_port: 9080
nginx_promtail_public_port: 39100
nginx_query_svc_local_port: 8007
nginx_query_svc_public_port: 39123