####### BOOTSTRAP ########
ansible_user: dataops
initial_user: root
bootstrap_user: dataops
backup_user: dataops_backup
github_pubkeys:
  - Bee0933

upgrade_all_packages: false
docker_users: "{{bootstrap_user}}"
docker_daily_prune: true

####### src-server ########
sftp_user: dataops
sftp_password: dataops
sftp_dir: /home/{{ ansible_user }}/sftp_data
sftp_remote_dir: /home/sftp
sftp_template_data: "{{ sftp_dir }}/template"
sftp_docker_image: emberstack/sftp
sftp_port: 2222
files_to_upload:                       # List of files to upload
  - "for-hire.csv"
  - "green-taxi.csv"
  - "yellow-taxi.csv"

# postgres DWH
postgres_docker_image: postgres
postgres_docker_image_tag: 13
postgres_container_name: postgres_dwh
postgres_database: postgres
postgres_password: root
postgres_user: root
postgres_port: 5432
postgres_dwh_user: dataops
postgres_dwh_user_password: dataops
postgres_dwh_database: dataops_db
postgres_data_dir: /opt/postgres/data
postgres_config_dir: /opt/postgres/config
postgres_log_dir: /var/log/postgresql
# pg configs
pg_addr: 0.0.0.0/0
pg_shared_buffers: 1GB
pg_work_mem: 16MB
pg_maintenance_work_mem: 512MB
pg_max_connections: 100


###### Airbtye-server ######
airbyte_email: user@dataops.com
airtbyte_pasword: dataops
airbyte_iac_path: /templates/
airbyte_sftp_src_dir: /sftp
airbyte_port: 8000
airbyte_sftp_filetype: csv
airbyte_sftp_file_pattern: "sample_*"
airbyte_sync_mode: full_refresh_append
airbyte_src_stream_name: sample_01.csv
airbyte_sync_cron: 0 0 * * * ?


###### Storage Server #######
minio_docker_image: quay.io/minio/minio
minio_docker_image_tag: latest
minio_container_name: minio
minio_base_dir: ./minio
minio_data_dir: minio/data
minio_console_port: 9001
minio_api_port: 9000
minio_root_usr: dataops
minio_root_password: dataops123
minio_mc_docker_image: minio/mc
minio_mc_docker_image_tag: latest
minio_mc_client: dmlminio
minio_bucket_name: rawdata
minio_bucket_path: /
minio_bucket_region: us-east-1


######## Query Layer #########
