---
- name: start metrics on platform
  hosts: all
  gather_facts: true
  become: true
  
  tasks:
    - name: Create Promtail dir
      file:
        path: "{{promtail_dir}}"
        state: directory

    - name: Promtail config file
      template:
        src: templates/promtail.yml
        dest: "{{promtail_config_file_path}}"

    # run node exporter
    - name: Run node_exporter container
      community.docker.docker_container:
        name: "{{ node_exporter_container_name }}"
        image: "{{ node_exporter_container_image }}"
        state: started
        restart_policy: always
        stop_timeout: "{{ node_exporter_container_stop_timeout }}"
        ports:
          - "{{ node_exporter_local_port }}:{{ node_exporter_local_port }}"  # Exposes the specified port
        volumes: "{{ node_exporter_container_volumes }}"
        env: "{{ node_exporter_container_env }}"
        networks: "{{ node_exporter_container_networks }}"
        command: "{{ node_exporter_container_command }}"

    # start promptail
    - name: Start Promtail
      docker_container:
        name: promtail
        state: started
        image: "{{ promtail_docker_imagename }}:{{promtail_docker_version}}"
        pull: true
        command: "-config.file={{ promtail_config_file_path }}"
        volumes:
          - "{{promtail_dir}}:{{promtail_dir}}"
          - "/var/log:/var/log"
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
        restart: true
        network_mode: host
        log_driver: json-file
        log_options:
          max-file: "10"
          max-size: 30m
          mode: non-blocking
          max-buffer-size: 4m