---
- name: start storsge server
  hosts: storage-server-0
  gather_facts: true
  become: true
  
  tasks:
    - name: Create MinIO data directory
      ansible.builtin.file:
        path: "./{{ minio_data_dir }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Template mc docker-compose file
      template:
        src: ./templates/docker-compose.yaml.j2
        dest: "{{ minio_base_dir }}/docker-compose.yaml"
    
    - name: Run MinIO container
      community.docker.docker_container:
        name: "{{ minio_container_name }}"
        image: "{{ minio_docker_image }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ minio_console_port }}:{{ minio_console_port }}"
          - "{{ minio_api_port }}:{{ minio_api_port }}"
        volumes:
          - "./{{ minio_data_dir }}:/data"
        env:
          MINIO_ROOT_USER: "{{ minio_root_usr }}"
          MINIO_ROOT_PASSWORD: "{{ minio_root_password }}"
        command: server /data --console-address ":{{ minio_console_port }}"
        labels:
          minio_log: "true"
          promtail_logging: "true"
          scrape_location: "minio"
          client_name: "minio-svc"
          traefik.enable: "true"
          traefik.http.routers.minio-http.entrypoints: "web"
        networks:
          - name: "traefik_{{ traefik_server_docker_network }}"
    
    - name: Wait for MinIO to start
      wait_for:
        port: "{{ minio_console_port }}"
        timeout: 200
    
    - name: Run Docker Compose up
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ minio_base_dir }}"
      become: true
      