---
- name: start src server sftp and postgres DWH
  hosts: src-server-0
  gather_facts: true
  become: true
  
  tasks:
    - name: create sftp_data dir
      file:
        path: "{{sftp_dir}}"
        state: directory

    - name: create sftp_template_data dir
      file:
        path: "{{ sftp_template_data }}"
        state: directory

    - name: Template sftp config file
      template:
        src: ./templates/sftp.json.j2
        dest: "{{ sftp_dir }}/sftp.json"

    - name: Copy template files to the remote machine
      copy:
        src: "templates/init-data/{{ item }}"
        dest: "{{ sftp_template_data }}/{{ item }}"
      loop: "{{ files_to_upload }}"
    
    - name: Run SFTP container
      docker_container:
        name: sftp
        image: "{{ sftp_docker_image }}"
        ports:
          - "{{ sftp_port }}:22"
        volumes:
          - "{{ sftp_dir }}/sftp.json:/app/config/sftp.json:ro"
          - "{{ sftp_dir }}:{{ sftp_remote_dir }}"
        state: started
        restart_policy: always
        labels:
          promtail_logging: "true"
          scrape_location: "sftp"
          client_name: "sftp-svc"
    
    - name: Wait for SFTP server to be ready
      wait_for:
        port: "{{ sftp_port }}"
        delay: 10
        timeout: 60

    - name: Remove entry from known_hosts
      command: ssh-keygen -f '/root/.ssh/known_hosts' -R '[{{ ansible_host }}]:{{ sftp_port }}'
      register: ssh_keygen_result
      ignore_errors: true
    
    - name: Upload files via SFTP with sshpass
      command: >
        sshpass -p "{{ sftp_password }}" sftp -v -o StrictHostKeyChecking=no -oPort={{ sftp_port }} {{ sftp_user }}@{{ ansible_host }}
      args:
        stdin: |
          {% for file in files_to_upload %}
          put {{ sftp_template_data }}/{{ file }} /sftp/{{ file }}
          {% endfor %}
      register: sftp_output
      ignore_errors: false
      run_once: true

    - name: Display SFTP upload output
      debug:
        var: sftp_output.stdout_lines
    
    
    ###### Postgres server ##############
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ postgres_data_dir }}"
        - "{{ postgres_config_dir }}"
        - "{{ postgres_log_dir }}"
    
    # postgres main configs
    - name: Template postgresql.config file
      template:
        src: ./templates/postgresql.conf.j2
        dest: "{{ postgres_config_dir }}/postgresql.conf"

    # postgres security configs
    - name: Template pg_hba.conf file
      template:
        src: ./templates/pg_hba.conf.j2
        dest: "{{ postgres_config_dir }}/pg_hba.conf"
    
    - name: Debug PostgreSQL password variable
      debug:
        var: postgres_password

    - name: Run PostgreSQL in Docker
      docker_container:
        name: "{{ postgres_container_name }}"
        image: "{{ postgres_docker_image }}:{{ postgres_docker_image_tag }}"
        state: started
        restart_policy: unless-stopped
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_DB: "{{ postgres_database }}"
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - "{{ postgres_data_dir }}:/var/lib/postgresql/data"
          - "{{ postgres_config_dir }}/postgresql.conf:/etc/postgresql/postgresql.conf"
          - "{{ postgres_config_dir }}/pg_hba.conf:/etc/postgresql/pg_hba.conf"
          - "{{ postgres_log_dir }}:/var/log/postgresql"
        published_ports:
          - "{{ postgres_port }}:{{ postgres_port }}"
        command: -c config_file=/etc/postgresql/postgresql.conf
        labels:
          promtail_logging: "true"
          scrape_location: "postgres"
          client_name: "postgres-svc"
    
    # - name: Create a new PostgreSQL user
    #   command: >
    #     docker exec {{ postgres_container_name }} psql -U {{ postgres_user }} -d postgres -c "
    #       CREATE USER {{ postgres_dwh_user }} WITH PASSWORD '{{ postgres_dwh_user_password }}';
    #     "

    # - name: Create a new PostgreSQL database
    #   command: >
    #     docker exec {{ postgres_container_name }} psql -U {{ postgres_user }} -d postgres -c "
    #       CREATE DATABASE {{ postgres_dwh_database }} OWNER {{ postgres_dwh_user }};
    #     "

    # - name: Grant privileges on the database
    #   command: >
    #     docker exec {{ postgres_container_name }} psql -U {{ postgres_user }} -d postgres -c "
    #       GRANT ALL PRIVILEGES ON DATABASE {{ postgres_dwh_database }} TO {{ postgres_dwh_user }};
    #     "

    - name: Restart PostgreSQL Docker container
      command: docker restart {{ postgres_container_name }}


