---
- name: start storsge server
  hosts: storage-server-0
  gather_facts: true
  become: true
  
  tasks:
    - name: Create MinIO data directory
      ansible.builtin.file:
        path: "./{{ minio_data_dir }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Template mc docker-compose file
      template:
        src: ./templates/docker-compose.yaml.j2
        dest: "{{ minio_base_dir }}/docker-compose.yaml"
    
    - name: Run MinIO container
      community.docker.docker_container:
        name: "{{ minio_container_name }}"
        image: "{{ minio_docker_image }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ minio_console_port }}:{{ minio_console_port }}"
          - "{{ minio_api_port }}:{{ minio_api_port }}"
        volumes:
          - "./{{ minio_data_dir }}:/data"
        env:
          MINIO_ROOT_USER: "dataops"
          MINIO_ROOT_PASSWORD: "dataops123"
          MINIO_SERVER_ACCESS_KEY: "{{ minio_access_key }}"
          MINIO_SERVER_SECRET_KEY: "{{ minio_secret_key }}"
        command: server /data --console-address ":{{ minio_console_port }}"
    
    - name: Wait for MinIO to start
      wait_for:
        port: "{{ minio_console_port }}"
        timeout: 100
    
    - name: Run Docker Compose up
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ minio_base_dir }}"
      become: true