name: Terraform Lint

on:
  # Trigger the workflow on push or pull request events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install TFLint
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    # Run TFLint with --recursive to lint all Terraform files in subdirectories
    - name: Run Terraform Lint
      run: |
        tflint --recursive

    # (Optional) Fail if lint errors are found
    - name: Fail on lint errors
      if: failure()
      run: echo "Terraform lint check failed!" && exit 1
